I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/quiz.rpy", line 638, in script
    $ n = str(get_sents_len() + 20) #estimate number of keywords
  File "game/quiz.rpy", line 638, in <module>
    $ n = str(get_sents_len() + 20) #estimate number of keywords
  File "game/quiz.rpy", line 76, in get_sents_len
    with open(file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\renpy-8.1.3-sdk\\kodigo/game/python/docs/Quiz.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/quiz.rpy", line 638, in script
    $ n = str(get_sents_len() + 20) #estimate number of keywords
  File "D:\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/quiz.rpy", line 638, in <module>
    $ n = str(get_sents_len() + 20) #estimate number of keywords
  File "game/quiz.rpy", line 76, in get_sents_len
    with open(file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\renpy-8.1.3-sdk\\kodigo/game/python/docs/Quiz.json'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Kodigo 1.0
Wed Mar 27 11:24:52 2024
